package org.fbi.linking.server.lrbmargin.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.linking.server.lrbmargin.repository.model.LrbMargTxn;
import org.fbi.linking.server.lrbmargin.repository.model.LrbMargTxnExample;

public interface LrbMargTxnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    int countByExample(LrbMargTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    int deleteByExample(LrbMargTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    int deleteByPrimaryKey(String inbankflcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    int insert(LrbMargTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    int insertSelective(LrbMargTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    List<LrbMargTxn> selectByExample(LrbMargTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    LrbMargTxn selectByPrimaryKey(String inbankflcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    int updateByExampleSelective(@Param("record") LrbMargTxn record, @Param("example") LrbMargTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    int updateByExample(@Param("record") LrbMargTxn record, @Param("example") LrbMargTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    int updateByPrimaryKeySelective(LrbMargTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    int updateByPrimaryKey(LrbMargTxn record);
}