package org.fbi.linking.server.lrbmargin.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class LrbMargActExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public LrbMargActExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInstcodeIsNull() {
            addCriterion("INSTCODE is null");
            return (Criteria) this;
        }

        public Criteria andInstcodeIsNotNull() {
            addCriterion("INSTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andInstcodeEqualTo(String value) {
            addCriterion("INSTCODE =", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeNotEqualTo(String value) {
            addCriterion("INSTCODE <>", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeGreaterThan(String value) {
            addCriterion("INSTCODE >", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeGreaterThanOrEqualTo(String value) {
            addCriterion("INSTCODE >=", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeLessThan(String value) {
            addCriterion("INSTCODE <", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeLessThanOrEqualTo(String value) {
            addCriterion("INSTCODE <=", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeLike(String value) {
            addCriterion("INSTCODE like", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeNotLike(String value) {
            addCriterion("INSTCODE not like", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeIn(List<String> values) {
            addCriterion("INSTCODE in", values, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeNotIn(List<String> values) {
            addCriterion("INSTCODE not in", values, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeBetween(String value1, String value2) {
            addCriterion("INSTCODE between", value1, value2, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeNotBetween(String value1, String value2) {
            addCriterion("INSTCODE not between", value1, value2, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstseqIsNull() {
            addCriterion("INSTSEQ is null");
            return (Criteria) this;
        }

        public Criteria andInstseqIsNotNull() {
            addCriterion("INSTSEQ is not null");
            return (Criteria) this;
        }

        public Criteria andInstseqEqualTo(String value) {
            addCriterion("INSTSEQ =", value, "instseq");
            return (Criteria) this;
        }

        public Criteria andInstseqNotEqualTo(String value) {
            addCriterion("INSTSEQ <>", value, "instseq");
            return (Criteria) this;
        }

        public Criteria andInstseqGreaterThan(String value) {
            addCriterion("INSTSEQ >", value, "instseq");
            return (Criteria) this;
        }

        public Criteria andInstseqGreaterThanOrEqualTo(String value) {
            addCriterion("INSTSEQ >=", value, "instseq");
            return (Criteria) this;
        }

        public Criteria andInstseqLessThan(String value) {
            addCriterion("INSTSEQ <", value, "instseq");
            return (Criteria) this;
        }

        public Criteria andInstseqLessThanOrEqualTo(String value) {
            addCriterion("INSTSEQ <=", value, "instseq");
            return (Criteria) this;
        }

        public Criteria andInstseqLike(String value) {
            addCriterion("INSTSEQ like", value, "instseq");
            return (Criteria) this;
        }

        public Criteria andInstseqNotLike(String value) {
            addCriterion("INSTSEQ not like", value, "instseq");
            return (Criteria) this;
        }

        public Criteria andInstseqIn(List<String> values) {
            addCriterion("INSTSEQ in", values, "instseq");
            return (Criteria) this;
        }

        public Criteria andInstseqNotIn(List<String> values) {
            addCriterion("INSTSEQ not in", values, "instseq");
            return (Criteria) this;
        }

        public Criteria andInstseqBetween(String value1, String value2) {
            addCriterion("INSTSEQ between", value1, value2, "instseq");
            return (Criteria) this;
        }

        public Criteria andInstseqNotBetween(String value1, String value2) {
            addCriterion("INSTSEQ not between", value1, value2, "instseq");
            return (Criteria) this;
        }

        public Criteria andMatudayIsNull() {
            addCriterion("MATUDAY is null");
            return (Criteria) this;
        }

        public Criteria andMatudayIsNotNull() {
            addCriterion("MATUDAY is not null");
            return (Criteria) this;
        }

        public Criteria andMatudayEqualTo(String value) {
            addCriterion("MATUDAY =", value, "matuday");
            return (Criteria) this;
        }

        public Criteria andMatudayNotEqualTo(String value) {
            addCriterion("MATUDAY <>", value, "matuday");
            return (Criteria) this;
        }

        public Criteria andMatudayGreaterThan(String value) {
            addCriterion("MATUDAY >", value, "matuday");
            return (Criteria) this;
        }

        public Criteria andMatudayGreaterThanOrEqualTo(String value) {
            addCriterion("MATUDAY >=", value, "matuday");
            return (Criteria) this;
        }

        public Criteria andMatudayLessThan(String value) {
            addCriterion("MATUDAY <", value, "matuday");
            return (Criteria) this;
        }

        public Criteria andMatudayLessThanOrEqualTo(String value) {
            addCriterion("MATUDAY <=", value, "matuday");
            return (Criteria) this;
        }

        public Criteria andMatudayLike(String value) {
            addCriterion("MATUDAY like", value, "matuday");
            return (Criteria) this;
        }

        public Criteria andMatudayNotLike(String value) {
            addCriterion("MATUDAY not like", value, "matuday");
            return (Criteria) this;
        }

        public Criteria andMatudayIn(List<String> values) {
            addCriterion("MATUDAY in", values, "matuday");
            return (Criteria) this;
        }

        public Criteria andMatudayNotIn(List<String> values) {
            addCriterion("MATUDAY not in", values, "matuday");
            return (Criteria) this;
        }

        public Criteria andMatudayBetween(String value1, String value2) {
            addCriterion("MATUDAY between", value1, value2, "matuday");
            return (Criteria) this;
        }

        public Criteria andMatudayNotBetween(String value1, String value2) {
            addCriterion("MATUDAY not between", value1, value2, "matuday");
            return (Criteria) this;
        }

        public Criteria andAcctnoIsNull() {
            addCriterion("ACCTNO is null");
            return (Criteria) this;
        }

        public Criteria andAcctnoIsNotNull() {
            addCriterion("ACCTNO is not null");
            return (Criteria) this;
        }

        public Criteria andAcctnoEqualTo(String value) {
            addCriterion("ACCTNO =", value, "acctno");
            return (Criteria) this;
        }

        public Criteria andAcctnoNotEqualTo(String value) {
            addCriterion("ACCTNO <>", value, "acctno");
            return (Criteria) this;
        }

        public Criteria andAcctnoGreaterThan(String value) {
            addCriterion("ACCTNO >", value, "acctno");
            return (Criteria) this;
        }

        public Criteria andAcctnoGreaterThanOrEqualTo(String value) {
            addCriterion("ACCTNO >=", value, "acctno");
            return (Criteria) this;
        }

        public Criteria andAcctnoLessThan(String value) {
            addCriterion("ACCTNO <", value, "acctno");
            return (Criteria) this;
        }

        public Criteria andAcctnoLessThanOrEqualTo(String value) {
            addCriterion("ACCTNO <=", value, "acctno");
            return (Criteria) this;
        }

        public Criteria andAcctnoLike(String value) {
            addCriterion("ACCTNO like", value, "acctno");
            return (Criteria) this;
        }

        public Criteria andAcctnoNotLike(String value) {
            addCriterion("ACCTNO not like", value, "acctno");
            return (Criteria) this;
        }

        public Criteria andAcctnoIn(List<String> values) {
            addCriterion("ACCTNO in", values, "acctno");
            return (Criteria) this;
        }

        public Criteria andAcctnoNotIn(List<String> values) {
            addCriterion("ACCTNO not in", values, "acctno");
            return (Criteria) this;
        }

        public Criteria andAcctnoBetween(String value1, String value2) {
            addCriterion("ACCTNO between", value1, value2, "acctno");
            return (Criteria) this;
        }

        public Criteria andAcctnoNotBetween(String value1, String value2) {
            addCriterion("ACCTNO not between", value1, value2, "acctno");
            return (Criteria) this;
        }

        public Criteria andCbsActnoIsNull() {
            addCriterion("CBS_ACTNO is null");
            return (Criteria) this;
        }

        public Criteria andCbsActnoIsNotNull() {
            addCriterion("CBS_ACTNO is not null");
            return (Criteria) this;
        }

        public Criteria andCbsActnoEqualTo(String value) {
            addCriterion("CBS_ACTNO =", value, "cbsActno");
            return (Criteria) this;
        }

        public Criteria andCbsActnoNotEqualTo(String value) {
            addCriterion("CBS_ACTNO <>", value, "cbsActno");
            return (Criteria) this;
        }

        public Criteria andCbsActnoGreaterThan(String value) {
            addCriterion("CBS_ACTNO >", value, "cbsActno");
            return (Criteria) this;
        }

        public Criteria andCbsActnoGreaterThanOrEqualTo(String value) {
            addCriterion("CBS_ACTNO >=", value, "cbsActno");
            return (Criteria) this;
        }

        public Criteria andCbsActnoLessThan(String value) {
            addCriterion("CBS_ACTNO <", value, "cbsActno");
            return (Criteria) this;
        }

        public Criteria andCbsActnoLessThanOrEqualTo(String value) {
            addCriterion("CBS_ACTNO <=", value, "cbsActno");
            return (Criteria) this;
        }

        public Criteria andCbsActnoLike(String value) {
            addCriterion("CBS_ACTNO like", value, "cbsActno");
            return (Criteria) this;
        }

        public Criteria andCbsActnoNotLike(String value) {
            addCriterion("CBS_ACTNO not like", value, "cbsActno");
            return (Criteria) this;
        }

        public Criteria andCbsActnoIn(List<String> values) {
            addCriterion("CBS_ACTNO in", values, "cbsActno");
            return (Criteria) this;
        }

        public Criteria andCbsActnoNotIn(List<String> values) {
            addCriterion("CBS_ACTNO not in", values, "cbsActno");
            return (Criteria) this;
        }

        public Criteria andCbsActnoBetween(String value1, String value2) {
            addCriterion("CBS_ACTNO between", value1, value2, "cbsActno");
            return (Criteria) this;
        }

        public Criteria andCbsActnoNotBetween(String value1, String value2) {
            addCriterion("CBS_ACTNO not between", value1, value2, "cbsActno");
            return (Criteria) this;
        }

        public Criteria andActStsIsNull() {
            addCriterion("ACT_STS is null");
            return (Criteria) this;
        }

        public Criteria andActStsIsNotNull() {
            addCriterion("ACT_STS is not null");
            return (Criteria) this;
        }

        public Criteria andActStsEqualTo(String value) {
            addCriterion("ACT_STS =", value, "actSts");
            return (Criteria) this;
        }

        public Criteria andActStsNotEqualTo(String value) {
            addCriterion("ACT_STS <>", value, "actSts");
            return (Criteria) this;
        }

        public Criteria andActStsGreaterThan(String value) {
            addCriterion("ACT_STS >", value, "actSts");
            return (Criteria) this;
        }

        public Criteria andActStsGreaterThanOrEqualTo(String value) {
            addCriterion("ACT_STS >=", value, "actSts");
            return (Criteria) this;
        }

        public Criteria andActStsLessThan(String value) {
            addCriterion("ACT_STS <", value, "actSts");
            return (Criteria) this;
        }

        public Criteria andActStsLessThanOrEqualTo(String value) {
            addCriterion("ACT_STS <=", value, "actSts");
            return (Criteria) this;
        }

        public Criteria andActStsLike(String value) {
            addCriterion("ACT_STS like", value, "actSts");
            return (Criteria) this;
        }

        public Criteria andActStsNotLike(String value) {
            addCriterion("ACT_STS not like", value, "actSts");
            return (Criteria) this;
        }

        public Criteria andActStsIn(List<String> values) {
            addCriterion("ACT_STS in", values, "actSts");
            return (Criteria) this;
        }

        public Criteria andActStsNotIn(List<String> values) {
            addCriterion("ACT_STS not in", values, "actSts");
            return (Criteria) this;
        }

        public Criteria andActStsBetween(String value1, String value2) {
            addCriterion("ACT_STS between", value1, value2, "actSts");
            return (Criteria) this;
        }

        public Criteria andActStsNotBetween(String value1, String value2) {
            addCriterion("ACT_STS not between", value1, value2, "actSts");
            return (Criteria) this;
        }

        public Criteria andActBalIsNull() {
            addCriterion("ACT_BAL is null");
            return (Criteria) this;
        }

        public Criteria andActBalIsNotNull() {
            addCriterion("ACT_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andActBalEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL =", value, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalNotEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL <>", value, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalGreaterThan(BigDecimal value) {
            addCriterion("ACT_BAL >", value, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL >=", value, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalLessThan(BigDecimal value) {
            addCriterion("ACT_BAL <", value, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_BAL <=", value, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalIn(List<BigDecimal> values) {
            addCriterion("ACT_BAL in", values, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalNotIn(List<BigDecimal> values) {
            addCriterion("ACT_BAL not in", values, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_BAL between", value1, value2, "actBal");
            return (Criteria) this;
        }

        public Criteria andActBalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_BAL not between", value1, value2, "actBal");
            return (Criteria) this;
        }

        public Criteria andIntcPdtIsNull() {
            addCriterion("INTC_PDT is null");
            return (Criteria) this;
        }

        public Criteria andIntcPdtIsNotNull() {
            addCriterion("INTC_PDT is not null");
            return (Criteria) this;
        }

        public Criteria andIntcPdtEqualTo(BigDecimal value) {
            addCriterion("INTC_PDT =", value, "intcPdt");
            return (Criteria) this;
        }

        public Criteria andIntcPdtNotEqualTo(BigDecimal value) {
            addCriterion("INTC_PDT <>", value, "intcPdt");
            return (Criteria) this;
        }

        public Criteria andIntcPdtGreaterThan(BigDecimal value) {
            addCriterion("INTC_PDT >", value, "intcPdt");
            return (Criteria) this;
        }

        public Criteria andIntcPdtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INTC_PDT >=", value, "intcPdt");
            return (Criteria) this;
        }

        public Criteria andIntcPdtLessThan(BigDecimal value) {
            addCriterion("INTC_PDT <", value, "intcPdt");
            return (Criteria) this;
        }

        public Criteria andIntcPdtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INTC_PDT <=", value, "intcPdt");
            return (Criteria) this;
        }

        public Criteria andIntcPdtIn(List<BigDecimal> values) {
            addCriterion("INTC_PDT in", values, "intcPdt");
            return (Criteria) this;
        }

        public Criteria andIntcPdtNotIn(List<BigDecimal> values) {
            addCriterion("INTC_PDT not in", values, "intcPdt");
            return (Criteria) this;
        }

        public Criteria andIntcPdtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTC_PDT between", value1, value2, "intcPdt");
            return (Criteria) this;
        }

        public Criteria andIntcPdtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTC_PDT not between", value1, value2, "intcPdt");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtIsNull() {
            addCriterion("LAST_TXN_DT is null");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtIsNotNull() {
            addCriterion("LAST_TXN_DT is not null");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtEqualTo(String value) {
            addCriterion("LAST_TXN_DT =", value, "lastTxnDt");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtNotEqualTo(String value) {
            addCriterion("LAST_TXN_DT <>", value, "lastTxnDt");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtGreaterThan(String value) {
            addCriterion("LAST_TXN_DT >", value, "lastTxnDt");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_TXN_DT >=", value, "lastTxnDt");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtLessThan(String value) {
            addCriterion("LAST_TXN_DT <", value, "lastTxnDt");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtLessThanOrEqualTo(String value) {
            addCriterion("LAST_TXN_DT <=", value, "lastTxnDt");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtLike(String value) {
            addCriterion("LAST_TXN_DT like", value, "lastTxnDt");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtNotLike(String value) {
            addCriterion("LAST_TXN_DT not like", value, "lastTxnDt");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtIn(List<String> values) {
            addCriterion("LAST_TXN_DT in", values, "lastTxnDt");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtNotIn(List<String> values) {
            addCriterion("LAST_TXN_DT not in", values, "lastTxnDt");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtBetween(String value1, String value2) {
            addCriterion("LAST_TXN_DT between", value1, value2, "lastTxnDt");
            return (Criteria) this;
        }

        public Criteria andLastTxnDtNotBetween(String value1, String value2) {
            addCriterion("LAST_TXN_DT not between", value1, value2, "lastTxnDt");
            return (Criteria) this;
        }

        public Criteria andLastActBalIsNull() {
            addCriterion("LAST_ACT_BAL is null");
            return (Criteria) this;
        }

        public Criteria andLastActBalIsNotNull() {
            addCriterion("LAST_ACT_BAL is not null");
            return (Criteria) this;
        }

        public Criteria andLastActBalEqualTo(BigDecimal value) {
            addCriterion("LAST_ACT_BAL =", value, "lastActBal");
            return (Criteria) this;
        }

        public Criteria andLastActBalNotEqualTo(BigDecimal value) {
            addCriterion("LAST_ACT_BAL <>", value, "lastActBal");
            return (Criteria) this;
        }

        public Criteria andLastActBalGreaterThan(BigDecimal value) {
            addCriterion("LAST_ACT_BAL >", value, "lastActBal");
            return (Criteria) this;
        }

        public Criteria andLastActBalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAST_ACT_BAL >=", value, "lastActBal");
            return (Criteria) this;
        }

        public Criteria andLastActBalLessThan(BigDecimal value) {
            addCriterion("LAST_ACT_BAL <", value, "lastActBal");
            return (Criteria) this;
        }

        public Criteria andLastActBalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAST_ACT_BAL <=", value, "lastActBal");
            return (Criteria) this;
        }

        public Criteria andLastActBalIn(List<BigDecimal> values) {
            addCriterion("LAST_ACT_BAL in", values, "lastActBal");
            return (Criteria) this;
        }

        public Criteria andLastActBalNotIn(List<BigDecimal> values) {
            addCriterion("LAST_ACT_BAL not in", values, "lastActBal");
            return (Criteria) this;
        }

        public Criteria andLastActBalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAST_ACT_BAL between", value1, value2, "lastActBal");
            return (Criteria) this;
        }

        public Criteria andLastActBalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAST_ACT_BAL not between", value1, value2, "lastActBal");
            return (Criteria) this;
        }

        public Criteria andOpenActDateIsNull() {
            addCriterion("OPEN_ACT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOpenActDateIsNotNull() {
            addCriterion("OPEN_ACT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOpenActDateEqualTo(String value) {
            addCriterion("OPEN_ACT_DATE =", value, "openActDate");
            return (Criteria) this;
        }

        public Criteria andOpenActDateNotEqualTo(String value) {
            addCriterion("OPEN_ACT_DATE <>", value, "openActDate");
            return (Criteria) this;
        }

        public Criteria andOpenActDateGreaterThan(String value) {
            addCriterion("OPEN_ACT_DATE >", value, "openActDate");
            return (Criteria) this;
        }

        public Criteria andOpenActDateGreaterThanOrEqualTo(String value) {
            addCriterion("OPEN_ACT_DATE >=", value, "openActDate");
            return (Criteria) this;
        }

        public Criteria andOpenActDateLessThan(String value) {
            addCriterion("OPEN_ACT_DATE <", value, "openActDate");
            return (Criteria) this;
        }

        public Criteria andOpenActDateLessThanOrEqualTo(String value) {
            addCriterion("OPEN_ACT_DATE <=", value, "openActDate");
            return (Criteria) this;
        }

        public Criteria andOpenActDateLike(String value) {
            addCriterion("OPEN_ACT_DATE like", value, "openActDate");
            return (Criteria) this;
        }

        public Criteria andOpenActDateNotLike(String value) {
            addCriterion("OPEN_ACT_DATE not like", value, "openActDate");
            return (Criteria) this;
        }

        public Criteria andOpenActDateIn(List<String> values) {
            addCriterion("OPEN_ACT_DATE in", values, "openActDate");
            return (Criteria) this;
        }

        public Criteria andOpenActDateNotIn(List<String> values) {
            addCriterion("OPEN_ACT_DATE not in", values, "openActDate");
            return (Criteria) this;
        }

        public Criteria andOpenActDateBetween(String value1, String value2) {
            addCriterion("OPEN_ACT_DATE between", value1, value2, "openActDate");
            return (Criteria) this;
        }

        public Criteria andOpenActDateNotBetween(String value1, String value2) {
            addCriterion("OPEN_ACT_DATE not between", value1, value2, "openActDate");
            return (Criteria) this;
        }

        public Criteria andCloseActDateIsNull() {
            addCriterion("CLOSE_ACT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCloseActDateIsNotNull() {
            addCriterion("CLOSE_ACT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCloseActDateEqualTo(String value) {
            addCriterion("CLOSE_ACT_DATE =", value, "closeActDate");
            return (Criteria) this;
        }

        public Criteria andCloseActDateNotEqualTo(String value) {
            addCriterion("CLOSE_ACT_DATE <>", value, "closeActDate");
            return (Criteria) this;
        }

        public Criteria andCloseActDateGreaterThan(String value) {
            addCriterion("CLOSE_ACT_DATE >", value, "closeActDate");
            return (Criteria) this;
        }

        public Criteria andCloseActDateGreaterThanOrEqualTo(String value) {
            addCriterion("CLOSE_ACT_DATE >=", value, "closeActDate");
            return (Criteria) this;
        }

        public Criteria andCloseActDateLessThan(String value) {
            addCriterion("CLOSE_ACT_DATE <", value, "closeActDate");
            return (Criteria) this;
        }

        public Criteria andCloseActDateLessThanOrEqualTo(String value) {
            addCriterion("CLOSE_ACT_DATE <=", value, "closeActDate");
            return (Criteria) this;
        }

        public Criteria andCloseActDateLike(String value) {
            addCriterion("CLOSE_ACT_DATE like", value, "closeActDate");
            return (Criteria) this;
        }

        public Criteria andCloseActDateNotLike(String value) {
            addCriterion("CLOSE_ACT_DATE not like", value, "closeActDate");
            return (Criteria) this;
        }

        public Criteria andCloseActDateIn(List<String> values) {
            addCriterion("CLOSE_ACT_DATE in", values, "closeActDate");
            return (Criteria) this;
        }

        public Criteria andCloseActDateNotIn(List<String> values) {
            addCriterion("CLOSE_ACT_DATE not in", values, "closeActDate");
            return (Criteria) this;
        }

        public Criteria andCloseActDateBetween(String value1, String value2) {
            addCriterion("CLOSE_ACT_DATE between", value1, value2, "closeActDate");
            return (Criteria) this;
        }

        public Criteria andCloseActDateNotBetween(String value1, String value2) {
            addCriterion("CLOSE_ACT_DATE not between", value1, value2, "closeActDate");
            return (Criteria) this;
        }

        public Criteria andFrzActDateIsNull() {
            addCriterion("FRZ_ACT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andFrzActDateIsNotNull() {
            addCriterion("FRZ_ACT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andFrzActDateEqualTo(String value) {
            addCriterion("FRZ_ACT_DATE =", value, "frzActDate");
            return (Criteria) this;
        }

        public Criteria andFrzActDateNotEqualTo(String value) {
            addCriterion("FRZ_ACT_DATE <>", value, "frzActDate");
            return (Criteria) this;
        }

        public Criteria andFrzActDateGreaterThan(String value) {
            addCriterion("FRZ_ACT_DATE >", value, "frzActDate");
            return (Criteria) this;
        }

        public Criteria andFrzActDateGreaterThanOrEqualTo(String value) {
            addCriterion("FRZ_ACT_DATE >=", value, "frzActDate");
            return (Criteria) this;
        }

        public Criteria andFrzActDateLessThan(String value) {
            addCriterion("FRZ_ACT_DATE <", value, "frzActDate");
            return (Criteria) this;
        }

        public Criteria andFrzActDateLessThanOrEqualTo(String value) {
            addCriterion("FRZ_ACT_DATE <=", value, "frzActDate");
            return (Criteria) this;
        }

        public Criteria andFrzActDateLike(String value) {
            addCriterion("FRZ_ACT_DATE like", value, "frzActDate");
            return (Criteria) this;
        }

        public Criteria andFrzActDateNotLike(String value) {
            addCriterion("FRZ_ACT_DATE not like", value, "frzActDate");
            return (Criteria) this;
        }

        public Criteria andFrzActDateIn(List<String> values) {
            addCriterion("FRZ_ACT_DATE in", values, "frzActDate");
            return (Criteria) this;
        }

        public Criteria andFrzActDateNotIn(List<String> values) {
            addCriterion("FRZ_ACT_DATE not in", values, "frzActDate");
            return (Criteria) this;
        }

        public Criteria andFrzActDateBetween(String value1, String value2) {
            addCriterion("FRZ_ACT_DATE between", value1, value2, "frzActDate");
            return (Criteria) this;
        }

        public Criteria andFrzActDateNotBetween(String value1, String value2) {
            addCriterion("FRZ_ACT_DATE not between", value1, value2, "frzActDate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNull() {
            addCriterion("RECVERSION is null");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNotNull() {
            addCriterion("RECVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andRecversionEqualTo(Integer value) {
            addCriterion("RECVERSION =", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotEqualTo(Integer value) {
            addCriterion("RECVERSION <>", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThan(Integer value) {
            addCriterion("RECVERSION >", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThanOrEqualTo(Integer value) {
            addCriterion("RECVERSION >=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThan(Integer value) {
            addCriterion("RECVERSION <", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThanOrEqualTo(Integer value) {
            addCriterion("RECVERSION <=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionIn(List<Integer> values) {
            addCriterion("RECVERSION in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotIn(List<Integer> values) {
            addCriterion("RECVERSION not in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionBetween(Integer value1, Integer value2) {
            addCriterion("RECVERSION between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotBetween(Integer value1, Integer value2) {
            addCriterion("RECVERSION not between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnIsNull() {
            addCriterion("IF_TIA_SN is null");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnIsNotNull() {
            addCriterion("IF_TIA_SN is not null");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnEqualTo(String value) {
            addCriterion("IF_TIA_SN =", value, "ifTiaSn");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnNotEqualTo(String value) {
            addCriterion("IF_TIA_SN <>", value, "ifTiaSn");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnGreaterThan(String value) {
            addCriterion("IF_TIA_SN >", value, "ifTiaSn");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnGreaterThanOrEqualTo(String value) {
            addCriterion("IF_TIA_SN >=", value, "ifTiaSn");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnLessThan(String value) {
            addCriterion("IF_TIA_SN <", value, "ifTiaSn");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnLessThanOrEqualTo(String value) {
            addCriterion("IF_TIA_SN <=", value, "ifTiaSn");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnLike(String value) {
            addCriterion("IF_TIA_SN like", value, "ifTiaSn");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnNotLike(String value) {
            addCriterion("IF_TIA_SN not like", value, "ifTiaSn");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnIn(List<String> values) {
            addCriterion("IF_TIA_SN in", values, "ifTiaSn");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnNotIn(List<String> values) {
            addCriterion("IF_TIA_SN not in", values, "ifTiaSn");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnBetween(String value1, String value2) {
            addCriterion("IF_TIA_SN between", value1, value2, "ifTiaSn");
            return (Criteria) this;
        }

        public Criteria andIfTiaSnNotBetween(String value1, String value2) {
            addCriterion("IF_TIA_SN not between", value1, value2, "ifTiaSn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 06 13:12:08 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LNK.LRB_MARG_ACT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}