package org.fbi.linking.server.lrbmargin.repository.model;

import java.math.BigDecimal;

public class LrbMargTxn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.INBANKFLCODE
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private String inbankflcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.INSTCODE
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private String instcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.INDATE
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private String indate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.INAMOUNT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private BigDecimal inamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.INNAME
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private String inname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.INACCT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private String inacct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.INMEMO
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private String inmemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.RESULT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.ADDWORD
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private String addword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.OPAC_BRID
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private String opacBrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.TXAC_BRID
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private String txacBrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.OPR1_NO
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private String opr1No;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.OPR2_NO
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private String opr2No;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LNK.LRB_MARG_TXN.REMARK
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.INBANKFLCODE
     *
     * @return the value of LNK.LRB_MARG_TXN.INBANKFLCODE
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getInbankflcode() {
        return inbankflcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.INBANKFLCODE
     *
     * @param inbankflcode the value for LNK.LRB_MARG_TXN.INBANKFLCODE
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setInbankflcode(String inbankflcode) {
        this.inbankflcode = inbankflcode == null ? null : inbankflcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.INSTCODE
     *
     * @return the value of LNK.LRB_MARG_TXN.INSTCODE
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getInstcode() {
        return instcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.INSTCODE
     *
     * @param instcode the value for LNK.LRB_MARG_TXN.INSTCODE
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setInstcode(String instcode) {
        this.instcode = instcode == null ? null : instcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.INDATE
     *
     * @return the value of LNK.LRB_MARG_TXN.INDATE
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.INDATE
     *
     * @param indate the value for LNK.LRB_MARG_TXN.INDATE
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setIndate(String indate) {
        this.indate = indate == null ? null : indate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.INAMOUNT
     *
     * @return the value of LNK.LRB_MARG_TXN.INAMOUNT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public BigDecimal getInamount() {
        return inamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.INAMOUNT
     *
     * @param inamount the value for LNK.LRB_MARG_TXN.INAMOUNT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setInamount(BigDecimal inamount) {
        this.inamount = inamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.INNAME
     *
     * @return the value of LNK.LRB_MARG_TXN.INNAME
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getInname() {
        return inname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.INNAME
     *
     * @param inname the value for LNK.LRB_MARG_TXN.INNAME
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setInname(String inname) {
        this.inname = inname == null ? null : inname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.INACCT
     *
     * @return the value of LNK.LRB_MARG_TXN.INACCT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getInacct() {
        return inacct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.INACCT
     *
     * @param inacct the value for LNK.LRB_MARG_TXN.INACCT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setInacct(String inacct) {
        this.inacct = inacct == null ? null : inacct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.INMEMO
     *
     * @return the value of LNK.LRB_MARG_TXN.INMEMO
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getInmemo() {
        return inmemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.INMEMO
     *
     * @param inmemo the value for LNK.LRB_MARG_TXN.INMEMO
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setInmemo(String inmemo) {
        this.inmemo = inmemo == null ? null : inmemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.RESULT
     *
     * @return the value of LNK.LRB_MARG_TXN.RESULT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.RESULT
     *
     * @param result the value for LNK.LRB_MARG_TXN.RESULT
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.ADDWORD
     *
     * @return the value of LNK.LRB_MARG_TXN.ADDWORD
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getAddword() {
        return addword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.ADDWORD
     *
     * @param addword the value for LNK.LRB_MARG_TXN.ADDWORD
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setAddword(String addword) {
        this.addword = addword == null ? null : addword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.OPAC_BRID
     *
     * @return the value of LNK.LRB_MARG_TXN.OPAC_BRID
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getOpacBrid() {
        return opacBrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.OPAC_BRID
     *
     * @param opacBrid the value for LNK.LRB_MARG_TXN.OPAC_BRID
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setOpacBrid(String opacBrid) {
        this.opacBrid = opacBrid == null ? null : opacBrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.TXAC_BRID
     *
     * @return the value of LNK.LRB_MARG_TXN.TXAC_BRID
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getTxacBrid() {
        return txacBrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.TXAC_BRID
     *
     * @param txacBrid the value for LNK.LRB_MARG_TXN.TXAC_BRID
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setTxacBrid(String txacBrid) {
        this.txacBrid = txacBrid == null ? null : txacBrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.OPR1_NO
     *
     * @return the value of LNK.LRB_MARG_TXN.OPR1_NO
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getOpr1No() {
        return opr1No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.OPR1_NO
     *
     * @param opr1No the value for LNK.LRB_MARG_TXN.OPR1_NO
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setOpr1No(String opr1No) {
        this.opr1No = opr1No == null ? null : opr1No.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.OPR2_NO
     *
     * @return the value of LNK.LRB_MARG_TXN.OPR2_NO
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getOpr2No() {
        return opr2No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.OPR2_NO
     *
     * @param opr2No the value for LNK.LRB_MARG_TXN.OPR2_NO
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setOpr2No(String opr2No) {
        this.opr2No = opr2No == null ? null : opr2No.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LNK.LRB_MARG_TXN.REMARK
     *
     * @return the value of LNK.LRB_MARG_TXN.REMARK
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LNK.LRB_MARG_TXN.REMARK
     *
     * @param remark the value for LNK.LRB_MARG_TXN.REMARK
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}