package org.fbi.linking.server.lrbmargin.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class LrbMargTxnExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public LrbMargTxnExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInbankflcodeIsNull() {
            addCriterion("INBANKFLCODE is null");
            return (Criteria) this;
        }

        public Criteria andInbankflcodeIsNotNull() {
            addCriterion("INBANKFLCODE is not null");
            return (Criteria) this;
        }

        public Criteria andInbankflcodeEqualTo(String value) {
            addCriterion("INBANKFLCODE =", value, "inbankflcode");
            return (Criteria) this;
        }

        public Criteria andInbankflcodeNotEqualTo(String value) {
            addCriterion("INBANKFLCODE <>", value, "inbankflcode");
            return (Criteria) this;
        }

        public Criteria andInbankflcodeGreaterThan(String value) {
            addCriterion("INBANKFLCODE >", value, "inbankflcode");
            return (Criteria) this;
        }

        public Criteria andInbankflcodeGreaterThanOrEqualTo(String value) {
            addCriterion("INBANKFLCODE >=", value, "inbankflcode");
            return (Criteria) this;
        }

        public Criteria andInbankflcodeLessThan(String value) {
            addCriterion("INBANKFLCODE <", value, "inbankflcode");
            return (Criteria) this;
        }

        public Criteria andInbankflcodeLessThanOrEqualTo(String value) {
            addCriterion("INBANKFLCODE <=", value, "inbankflcode");
            return (Criteria) this;
        }

        public Criteria andInbankflcodeLike(String value) {
            addCriterion("INBANKFLCODE like", value, "inbankflcode");
            return (Criteria) this;
        }

        public Criteria andInbankflcodeNotLike(String value) {
            addCriterion("INBANKFLCODE not like", value, "inbankflcode");
            return (Criteria) this;
        }

        public Criteria andInbankflcodeIn(List<String> values) {
            addCriterion("INBANKFLCODE in", values, "inbankflcode");
            return (Criteria) this;
        }

        public Criteria andInbankflcodeNotIn(List<String> values) {
            addCriterion("INBANKFLCODE not in", values, "inbankflcode");
            return (Criteria) this;
        }

        public Criteria andInbankflcodeBetween(String value1, String value2) {
            addCriterion("INBANKFLCODE between", value1, value2, "inbankflcode");
            return (Criteria) this;
        }

        public Criteria andInbankflcodeNotBetween(String value1, String value2) {
            addCriterion("INBANKFLCODE not between", value1, value2, "inbankflcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeIsNull() {
            addCriterion("INSTCODE is null");
            return (Criteria) this;
        }

        public Criteria andInstcodeIsNotNull() {
            addCriterion("INSTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andInstcodeEqualTo(String value) {
            addCriterion("INSTCODE =", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeNotEqualTo(String value) {
            addCriterion("INSTCODE <>", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeGreaterThan(String value) {
            addCriterion("INSTCODE >", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeGreaterThanOrEqualTo(String value) {
            addCriterion("INSTCODE >=", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeLessThan(String value) {
            addCriterion("INSTCODE <", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeLessThanOrEqualTo(String value) {
            addCriterion("INSTCODE <=", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeLike(String value) {
            addCriterion("INSTCODE like", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeNotLike(String value) {
            addCriterion("INSTCODE not like", value, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeIn(List<String> values) {
            addCriterion("INSTCODE in", values, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeNotIn(List<String> values) {
            addCriterion("INSTCODE not in", values, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeBetween(String value1, String value2) {
            addCriterion("INSTCODE between", value1, value2, "instcode");
            return (Criteria) this;
        }

        public Criteria andInstcodeNotBetween(String value1, String value2) {
            addCriterion("INSTCODE not between", value1, value2, "instcode");
            return (Criteria) this;
        }

        public Criteria andIndateIsNull() {
            addCriterion("INDATE is null");
            return (Criteria) this;
        }

        public Criteria andIndateIsNotNull() {
            addCriterion("INDATE is not null");
            return (Criteria) this;
        }

        public Criteria andIndateEqualTo(String value) {
            addCriterion("INDATE =", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateNotEqualTo(String value) {
            addCriterion("INDATE <>", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateGreaterThan(String value) {
            addCriterion("INDATE >", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateGreaterThanOrEqualTo(String value) {
            addCriterion("INDATE >=", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateLessThan(String value) {
            addCriterion("INDATE <", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateLessThanOrEqualTo(String value) {
            addCriterion("INDATE <=", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateLike(String value) {
            addCriterion("INDATE like", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateNotLike(String value) {
            addCriterion("INDATE not like", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateIn(List<String> values) {
            addCriterion("INDATE in", values, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateNotIn(List<String> values) {
            addCriterion("INDATE not in", values, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateBetween(String value1, String value2) {
            addCriterion("INDATE between", value1, value2, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateNotBetween(String value1, String value2) {
            addCriterion("INDATE not between", value1, value2, "indate");
            return (Criteria) this;
        }

        public Criteria andInamountIsNull() {
            addCriterion("INAMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andInamountIsNotNull() {
            addCriterion("INAMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andInamountEqualTo(BigDecimal value) {
            addCriterion("INAMOUNT =", value, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountNotEqualTo(BigDecimal value) {
            addCriterion("INAMOUNT <>", value, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountGreaterThan(BigDecimal value) {
            addCriterion("INAMOUNT >", value, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INAMOUNT >=", value, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountLessThan(BigDecimal value) {
            addCriterion("INAMOUNT <", value, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INAMOUNT <=", value, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountIn(List<BigDecimal> values) {
            addCriterion("INAMOUNT in", values, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountNotIn(List<BigDecimal> values) {
            addCriterion("INAMOUNT not in", values, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INAMOUNT between", value1, value2, "inamount");
            return (Criteria) this;
        }

        public Criteria andInamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INAMOUNT not between", value1, value2, "inamount");
            return (Criteria) this;
        }

        public Criteria andInnameIsNull() {
            addCriterion("INNAME is null");
            return (Criteria) this;
        }

        public Criteria andInnameIsNotNull() {
            addCriterion("INNAME is not null");
            return (Criteria) this;
        }

        public Criteria andInnameEqualTo(String value) {
            addCriterion("INNAME =", value, "inname");
            return (Criteria) this;
        }

        public Criteria andInnameNotEqualTo(String value) {
            addCriterion("INNAME <>", value, "inname");
            return (Criteria) this;
        }

        public Criteria andInnameGreaterThan(String value) {
            addCriterion("INNAME >", value, "inname");
            return (Criteria) this;
        }

        public Criteria andInnameGreaterThanOrEqualTo(String value) {
            addCriterion("INNAME >=", value, "inname");
            return (Criteria) this;
        }

        public Criteria andInnameLessThan(String value) {
            addCriterion("INNAME <", value, "inname");
            return (Criteria) this;
        }

        public Criteria andInnameLessThanOrEqualTo(String value) {
            addCriterion("INNAME <=", value, "inname");
            return (Criteria) this;
        }

        public Criteria andInnameLike(String value) {
            addCriterion("INNAME like", value, "inname");
            return (Criteria) this;
        }

        public Criteria andInnameNotLike(String value) {
            addCriterion("INNAME not like", value, "inname");
            return (Criteria) this;
        }

        public Criteria andInnameIn(List<String> values) {
            addCriterion("INNAME in", values, "inname");
            return (Criteria) this;
        }

        public Criteria andInnameNotIn(List<String> values) {
            addCriterion("INNAME not in", values, "inname");
            return (Criteria) this;
        }

        public Criteria andInnameBetween(String value1, String value2) {
            addCriterion("INNAME between", value1, value2, "inname");
            return (Criteria) this;
        }

        public Criteria andInnameNotBetween(String value1, String value2) {
            addCriterion("INNAME not between", value1, value2, "inname");
            return (Criteria) this;
        }

        public Criteria andInacctIsNull() {
            addCriterion("INACCT is null");
            return (Criteria) this;
        }

        public Criteria andInacctIsNotNull() {
            addCriterion("INACCT is not null");
            return (Criteria) this;
        }

        public Criteria andInacctEqualTo(String value) {
            addCriterion("INACCT =", value, "inacct");
            return (Criteria) this;
        }

        public Criteria andInacctNotEqualTo(String value) {
            addCriterion("INACCT <>", value, "inacct");
            return (Criteria) this;
        }

        public Criteria andInacctGreaterThan(String value) {
            addCriterion("INACCT >", value, "inacct");
            return (Criteria) this;
        }

        public Criteria andInacctGreaterThanOrEqualTo(String value) {
            addCriterion("INACCT >=", value, "inacct");
            return (Criteria) this;
        }

        public Criteria andInacctLessThan(String value) {
            addCriterion("INACCT <", value, "inacct");
            return (Criteria) this;
        }

        public Criteria andInacctLessThanOrEqualTo(String value) {
            addCriterion("INACCT <=", value, "inacct");
            return (Criteria) this;
        }

        public Criteria andInacctLike(String value) {
            addCriterion("INACCT like", value, "inacct");
            return (Criteria) this;
        }

        public Criteria andInacctNotLike(String value) {
            addCriterion("INACCT not like", value, "inacct");
            return (Criteria) this;
        }

        public Criteria andInacctIn(List<String> values) {
            addCriterion("INACCT in", values, "inacct");
            return (Criteria) this;
        }

        public Criteria andInacctNotIn(List<String> values) {
            addCriterion("INACCT not in", values, "inacct");
            return (Criteria) this;
        }

        public Criteria andInacctBetween(String value1, String value2) {
            addCriterion("INACCT between", value1, value2, "inacct");
            return (Criteria) this;
        }

        public Criteria andInacctNotBetween(String value1, String value2) {
            addCriterion("INACCT not between", value1, value2, "inacct");
            return (Criteria) this;
        }

        public Criteria andInmemoIsNull() {
            addCriterion("INMEMO is null");
            return (Criteria) this;
        }

        public Criteria andInmemoIsNotNull() {
            addCriterion("INMEMO is not null");
            return (Criteria) this;
        }

        public Criteria andInmemoEqualTo(String value) {
            addCriterion("INMEMO =", value, "inmemo");
            return (Criteria) this;
        }

        public Criteria andInmemoNotEqualTo(String value) {
            addCriterion("INMEMO <>", value, "inmemo");
            return (Criteria) this;
        }

        public Criteria andInmemoGreaterThan(String value) {
            addCriterion("INMEMO >", value, "inmemo");
            return (Criteria) this;
        }

        public Criteria andInmemoGreaterThanOrEqualTo(String value) {
            addCriterion("INMEMO >=", value, "inmemo");
            return (Criteria) this;
        }

        public Criteria andInmemoLessThan(String value) {
            addCriterion("INMEMO <", value, "inmemo");
            return (Criteria) this;
        }

        public Criteria andInmemoLessThanOrEqualTo(String value) {
            addCriterion("INMEMO <=", value, "inmemo");
            return (Criteria) this;
        }

        public Criteria andInmemoLike(String value) {
            addCriterion("INMEMO like", value, "inmemo");
            return (Criteria) this;
        }

        public Criteria andInmemoNotLike(String value) {
            addCriterion("INMEMO not like", value, "inmemo");
            return (Criteria) this;
        }

        public Criteria andInmemoIn(List<String> values) {
            addCriterion("INMEMO in", values, "inmemo");
            return (Criteria) this;
        }

        public Criteria andInmemoNotIn(List<String> values) {
            addCriterion("INMEMO not in", values, "inmemo");
            return (Criteria) this;
        }

        public Criteria andInmemoBetween(String value1, String value2) {
            addCriterion("INMEMO between", value1, value2, "inmemo");
            return (Criteria) this;
        }

        public Criteria andInmemoNotBetween(String value1, String value2) {
            addCriterion("INMEMO not between", value1, value2, "inmemo");
            return (Criteria) this;
        }

        public Criteria andResultIsNull() {
            addCriterion("RESULT is null");
            return (Criteria) this;
        }

        public Criteria andResultIsNotNull() {
            addCriterion("RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andResultEqualTo(String value) {
            addCriterion("RESULT =", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotEqualTo(String value) {
            addCriterion("RESULT <>", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThan(String value) {
            addCriterion("RESULT >", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThanOrEqualTo(String value) {
            addCriterion("RESULT >=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThan(String value) {
            addCriterion("RESULT <", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThanOrEqualTo(String value) {
            addCriterion("RESULT <=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLike(String value) {
            addCriterion("RESULT like", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotLike(String value) {
            addCriterion("RESULT not like", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultIn(List<String> values) {
            addCriterion("RESULT in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotIn(List<String> values) {
            addCriterion("RESULT not in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultBetween(String value1, String value2) {
            addCriterion("RESULT between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotBetween(String value1, String value2) {
            addCriterion("RESULT not between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andAddwordIsNull() {
            addCriterion("ADDWORD is null");
            return (Criteria) this;
        }

        public Criteria andAddwordIsNotNull() {
            addCriterion("ADDWORD is not null");
            return (Criteria) this;
        }

        public Criteria andAddwordEqualTo(String value) {
            addCriterion("ADDWORD =", value, "addword");
            return (Criteria) this;
        }

        public Criteria andAddwordNotEqualTo(String value) {
            addCriterion("ADDWORD <>", value, "addword");
            return (Criteria) this;
        }

        public Criteria andAddwordGreaterThan(String value) {
            addCriterion("ADDWORD >", value, "addword");
            return (Criteria) this;
        }

        public Criteria andAddwordGreaterThanOrEqualTo(String value) {
            addCriterion("ADDWORD >=", value, "addword");
            return (Criteria) this;
        }

        public Criteria andAddwordLessThan(String value) {
            addCriterion("ADDWORD <", value, "addword");
            return (Criteria) this;
        }

        public Criteria andAddwordLessThanOrEqualTo(String value) {
            addCriterion("ADDWORD <=", value, "addword");
            return (Criteria) this;
        }

        public Criteria andAddwordLike(String value) {
            addCriterion("ADDWORD like", value, "addword");
            return (Criteria) this;
        }

        public Criteria andAddwordNotLike(String value) {
            addCriterion("ADDWORD not like", value, "addword");
            return (Criteria) this;
        }

        public Criteria andAddwordIn(List<String> values) {
            addCriterion("ADDWORD in", values, "addword");
            return (Criteria) this;
        }

        public Criteria andAddwordNotIn(List<String> values) {
            addCriterion("ADDWORD not in", values, "addword");
            return (Criteria) this;
        }

        public Criteria andAddwordBetween(String value1, String value2) {
            addCriterion("ADDWORD between", value1, value2, "addword");
            return (Criteria) this;
        }

        public Criteria andAddwordNotBetween(String value1, String value2) {
            addCriterion("ADDWORD not between", value1, value2, "addword");
            return (Criteria) this;
        }

        public Criteria andOpacBridIsNull() {
            addCriterion("OPAC_BRID is null");
            return (Criteria) this;
        }

        public Criteria andOpacBridIsNotNull() {
            addCriterion("OPAC_BRID is not null");
            return (Criteria) this;
        }

        public Criteria andOpacBridEqualTo(String value) {
            addCriterion("OPAC_BRID =", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridNotEqualTo(String value) {
            addCriterion("OPAC_BRID <>", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridGreaterThan(String value) {
            addCriterion("OPAC_BRID >", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridGreaterThanOrEqualTo(String value) {
            addCriterion("OPAC_BRID >=", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridLessThan(String value) {
            addCriterion("OPAC_BRID <", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridLessThanOrEqualTo(String value) {
            addCriterion("OPAC_BRID <=", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridLike(String value) {
            addCriterion("OPAC_BRID like", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridNotLike(String value) {
            addCriterion("OPAC_BRID not like", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridIn(List<String> values) {
            addCriterion("OPAC_BRID in", values, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridNotIn(List<String> values) {
            addCriterion("OPAC_BRID not in", values, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridBetween(String value1, String value2) {
            addCriterion("OPAC_BRID between", value1, value2, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridNotBetween(String value1, String value2) {
            addCriterion("OPAC_BRID not between", value1, value2, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridIsNull() {
            addCriterion("TXAC_BRID is null");
            return (Criteria) this;
        }

        public Criteria andTxacBridIsNotNull() {
            addCriterion("TXAC_BRID is not null");
            return (Criteria) this;
        }

        public Criteria andTxacBridEqualTo(String value) {
            addCriterion("TXAC_BRID =", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridNotEqualTo(String value) {
            addCriterion("TXAC_BRID <>", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridGreaterThan(String value) {
            addCriterion("TXAC_BRID >", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridGreaterThanOrEqualTo(String value) {
            addCriterion("TXAC_BRID >=", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridLessThan(String value) {
            addCriterion("TXAC_BRID <", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridLessThanOrEqualTo(String value) {
            addCriterion("TXAC_BRID <=", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridLike(String value) {
            addCriterion("TXAC_BRID like", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridNotLike(String value) {
            addCriterion("TXAC_BRID not like", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridIn(List<String> values) {
            addCriterion("TXAC_BRID in", values, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridNotIn(List<String> values) {
            addCriterion("TXAC_BRID not in", values, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridBetween(String value1, String value2) {
            addCriterion("TXAC_BRID between", value1, value2, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridNotBetween(String value1, String value2) {
            addCriterion("TXAC_BRID not between", value1, value2, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andOpr1NoIsNull() {
            addCriterion("OPR1_NO is null");
            return (Criteria) this;
        }

        public Criteria andOpr1NoIsNotNull() {
            addCriterion("OPR1_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOpr1NoEqualTo(String value) {
            addCriterion("OPR1_NO =", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoNotEqualTo(String value) {
            addCriterion("OPR1_NO <>", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoGreaterThan(String value) {
            addCriterion("OPR1_NO >", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoGreaterThanOrEqualTo(String value) {
            addCriterion("OPR1_NO >=", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoLessThan(String value) {
            addCriterion("OPR1_NO <", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoLessThanOrEqualTo(String value) {
            addCriterion("OPR1_NO <=", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoLike(String value) {
            addCriterion("OPR1_NO like", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoNotLike(String value) {
            addCriterion("OPR1_NO not like", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoIn(List<String> values) {
            addCriterion("OPR1_NO in", values, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoNotIn(List<String> values) {
            addCriterion("OPR1_NO not in", values, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoBetween(String value1, String value2) {
            addCriterion("OPR1_NO between", value1, value2, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoNotBetween(String value1, String value2) {
            addCriterion("OPR1_NO not between", value1, value2, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoIsNull() {
            addCriterion("OPR2_NO is null");
            return (Criteria) this;
        }

        public Criteria andOpr2NoIsNotNull() {
            addCriterion("OPR2_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOpr2NoEqualTo(String value) {
            addCriterion("OPR2_NO =", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoNotEqualTo(String value) {
            addCriterion("OPR2_NO <>", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoGreaterThan(String value) {
            addCriterion("OPR2_NO >", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoGreaterThanOrEqualTo(String value) {
            addCriterion("OPR2_NO >=", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoLessThan(String value) {
            addCriterion("OPR2_NO <", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoLessThanOrEqualTo(String value) {
            addCriterion("OPR2_NO <=", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoLike(String value) {
            addCriterion("OPR2_NO like", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoNotLike(String value) {
            addCriterion("OPR2_NO not like", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoIn(List<String> values) {
            addCriterion("OPR2_NO in", values, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoNotIn(List<String> values) {
            addCriterion("OPR2_NO not in", values, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoBetween(String value1, String value2) {
            addCriterion("OPR2_NO between", value1, value2, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoNotBetween(String value1, String value2) {
            addCriterion("OPR2_NO not between", value1, value2, "opr2No");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 06 13:12:08 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LNK.LRB_MARG_TXN
     *
     * @mbggenerated Thu Nov 06 13:12:08 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}